### ISSUE TITLE
求问这是用python2还是python3运行的啊？

### ISSUE THREAD

**Issue by gitby2018** [talebook/my-calibre-webserver#4]
为什么无论用python2还是3运行都有错误提示？
其中一个，我一直搜不到答案。
Traceback (most recent call last):
  File "server.py", line 9, in <module>
    from webserver import server
  File "/root/calibre-server/webserver/server.py", line 6, in <module>
    import models
  File "/root/calibre-server/webserver/models.py", line 8, in <module>
    from social_sqlalchemy.storage import JSONType, SQLAlchemyMixin, SQLAlchemyUserMixin
ImportError: No module named social_sqlalchemy.storage

**Comment by oldiy** [comment]
python2

**Comment by gitby2018** [comment]
上面那个问题解决了，但是在“创建db“一步输入命令”python /data/release/www/calibre.talebook.org/my-calibre-server/server.py --syncdb“
后系统给了一个反馈是“[E 190214 10:33:06 server:76] read local_settings fail”，这个怎么解决呀？现在网站都打不开，nginx是启动正常的。

**Comment by talebook** [comment]
【read local_settings fail】这行日志不影响。
部署过程中如果有问题，可以加一下Q群303749730一起沟通下。之前文档写得不是特别完善。

**Comment by talebook** [comment]
https://github.com/talebook/my-calibre-webserver/blob/master/docs/INSTALL.zh_CN.md
可以参考这个安装文档。
