### ISSUE TITLE
单机版本如何批量生成图书的标签？

### ISSUE THREAD

**Issue by rodericliu** [talebook/my-calibre-webserver#6]
按照中文安装文档安装好单机版后，点开所有书籍，发现所有标签都是0，必须点到每本图书里面，选择从豆瓣更新书籍信息然后选择跳出的列表里的一个后才会生成标签。

有没有可以批量从豆瓣更新所有书籍信息的命令？

**Comment by talebook** [comment]
这个需要自己编写脚本批量处理了。代码库中有两个参考：
1、my-calibre-webserver/tools/update.sh
这个脚本是直接设置具体某本书的ISBN号码。原理是直接调用了db接口。调用完毕后需要重启server。

2、my-calibre-webserver/tools/tools.py
这个脚本是批量根据ISBN号码去豆瓣拉取书籍信息。脚本中有一些判断逻辑，如果comments、tags都有内容，就跳过；如果book id 小于某个值，也会跳过。因此这些都需要跟进自己的需求进行修改调整。

以上的脚本组合起来，思路就是 设置ISBN号 + 自动拉取填充。能解决大部分书籍的准确性问题。网页版的更新书籍信息，是根据标题搜索（可能不准/有多个结果），人工进行筛选的，不方便自动化处理。
